---
# Run with ansible-playbook <filename> -u root
#       (make sure to add the IPs of the machine you want to manage to an ansible hosts file first)
- hosts: all
  vars:
    # used for file paths
    site_name: "tutoriallinux"
    #used in the websites markup
    site_tilte: "testing"
    #used in the web server config file
    site_url: "www.tutoriallinux.com"

  tasks:
    - name: Install nginx
      package: name=nginx state=latest

    - name: Create website dir
      file: path="/var/www/{{ site_name }}" state=directory mode=0755

    - name: Create main nginx config file
      template: src=templates/nginx.conf dest=/etc/nginx/nginx.conf
      notify:
      - restart nginx 

    - name: Create nginx vhost config file
      template: src=templates/website.conf dest=/etc/nginx/conf.d/{{ site_name }}.conf
      notify:
      - restart nginx

    - name: Create Website
      template: src=templates/index.html dest=/var/www/{{ site_name }}/index.html

    - name: Remove default nginx vhost config
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify:
        - restart nginx


  handlers:
  # This handler is called multiple times above. It essentially just restarted the nginx service at each call
    - name: restart nginx
      service: name=nginx state=restarted

